# Generated by Django 3.1 on 2022-03-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
